# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "region" {
  type    = string
  default = "ap-southeast-1"
}

variable "shared_credentials_file" {
  type    = string
  default = "credentials"
}

variable "profile" {
  type    = string
  default = "default"
}

