---
- name: Wait for instance to be up after the reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 5
    timeout: 300
  become: false

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Add user to Docker group
  raw: sudo usermod -a -G docker ubuntu

- name: Enable Docker at startup
  raw: sudo systemctl enable docker

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
